spring:
  output:
    ansi:
      enabled: always # 콘솔 색상 변경
  thymeleaf:
        cache: false # 타임리프 캐시 종료
  prefix: file:src/main/resources/templates/ # 템플릿 파일 경로
  suffix: .html
  application:
    name: basic1

# server:
  # port: 8080

